[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache_forge"

# Solidity version
solc_version = "0.8.24"

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Test settings
fuzz_runs = 1000
invariant_runs = 256
invariant_depth = 15

# Gas reporting
gas_reports = ["*"]

# Remappings
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/",
]

[profile.ci]
fuzz_runs = 10000
invariant_runs = 1000
